### ISSUE TITLE
random *.tmp files listed in unstaged changes

### ISSUE THREAD

**Issue by raszpl** [sheabunge/GitPortable#14] opened 2015-12-06 18:54 UTC
unpacked
started GitGUIPortable.exe
created empty repository on github
clicked clone, cloned my freshly created empty repository to disk
unstaged changes lists some random garbage files, all with .tmp extension. Clicking rescan generates new group of random garbage tmp files.

![clipboard02](https://cloud.githubusercontent.com/assets/2623127/11614947/eeb343da-9c52-11e5-90f9-f21c54dd9382.jpg)

clicking on one of them generates popup "error loading file, could not read xx.tmp, no such file or dir"

*First time using git gui. No idea what Im doing.

**Comment by sheabunge** [comment] 2016-03-04 09:08
I am not able to reproduce this error. It's probably a bug in Git for Windows, which means that it's something that I can fix. Hopefully it will be resolved in a future version of Git. 

In the meantime, try recloning the repository and seeing if that makes a difference.

**Closed by sheabunge** 2016-03-04 09:08 UTC
